# 比較対象保存先
contact_list = C:\Users\yh980\SK\data\連絡先一覧.xlsx
ledger = C:\Users\yh980\SK\data\台帳.xlsx
ad_export = C:\Users\yh980\SK\data\AD_export_user.xlsx

# 比較結果保存先
delete_check_result = C:\Users\yh980\SK\result\削除ユーザー存在チェック結果.xlsx
ledger_ad_result = C:\Users\yh980\SK\result\台帳_AD比較結果.xlsx